#!/usr/bin/env python
import sys
import BaseHTTPServer
from SimpleHTTPServer import SimpleHTTPRequestHandler

HandlerClass = SimpleHTTPRequestHandler
ServerClass  = BaseHTTPServer.HTTPServer
Protocol     = "HTTP/1.0"
if sys.argv[1:]:
	address = sys.argv[1]
        port = int(sys.argv[2])
else:
        address = '127.0.0.1'
	port = 8000
server_address = (address, port)
HandlerClass.protocol_version = Protocol
httpd = ServerClass(server_address, HandlerClass) 
sa = httpd.socket.getsockname()
print "Serving HTTP on", sa[0], "port", sa[1], "..."
httpd.serve_forever()
